-- TEMPORARILY DISABLE RLS TO FIX RECURSION ISSUE
-- This script temporarily disables RLS on problematic tables to resolve stack depth exceeded errors

-- Disable RLS on all tables to break recursion
ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE gl_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE gl_mappings DISABLE ROW LEVEL SECURITY;
ALTER TABLE uoms DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE warehouses DISABLE ROW LEVEL SECURITY;
ALTER TABLE locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE bom_headers DISABLE ROW LEVEL SECURITY;
ALTER TABLE bom_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_centers DISABLE ROW LEVEL SECURITY;
ALTER TABLE labor_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE overhead_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE overhead_allocations DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_quants DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_moves DISABLE ROW LEVEL SECURITY;
ALTER TABLE cost_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE grns DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales_lines DISABLE ROW LEVEL SECURITY;

-- Drop the problematic policies
DROP POLICY IF EXISTS "Users can view their organizations" ON organizations;
DROP POLICY IF EXISTS "Users can view org memberships" ON user_organizations;
DROP POLICY IF EXISTS "Users can view org GL accounts" ON gl_accounts;

-- For testing purposes, we can re-enable RLS later with simpler policies
-- that don't cause recursion