import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import { Menu } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { ThemeToggle } from '@/components/theme-toggle'
import { LanguageToggle } from '@/components/language-toggle'
import { OrganizationSelector } from '@/components/organization-selector'
import { useUIStore } from '@/store/ui-store'
import { useAuthStore } from '@/store/auth-store'
import { useAuth } from '@/contexts/AuthContext'
import { cn } from '@/lib/utils'
import { HeaderBrand } from './HeaderBrand'
import